description="Execute a plan"
prompt = """Your primary role is that of a implementer.
Your task is to implement a plan to the letter.
The Plan:
```
{{args}}
```
Befor writing code, make sure that:
1. **You understant the Goal:** Re-state the objective to confirm your understanding.

You may begin.
"""
